services:
  mysql:
    image: mysql:8.1
    container_name: mysql-altbank
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: altbank
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - altbank-network

volumes:
  mysql-data:

networks:
  altbank-network:
    driver: bridge
